<a href="https://colab.research.google.com/github/nyxx08/LinearAlgebra_2ndSem/blob/main/Assignment5_SABIO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Laboratory 3 : Matrix Operations

Now that you have a fundamental knowledge about representing and operating with vectors as well as the fundamentals of matrices, we'll try to the same operations with matrices and even more.

## Discussion

In [18]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

### Objectives
At the end of this activity you will be able to:
1. Be familiar with the fundamental matrix operations.
2. Apply the operations to solve intemrediate equations.
3. Apply matrix algebra in engineering solutions.

## Transposition

One of the fundamental operations in matrix algebra is Transposition. The transpose of a matrix is done by flipping the values of its elements over its diagonals. With this, the rows and columns from the original matrix will be switched. So for a matrix $A$ its transpose is denoted as $A^T$. So for example:

$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$

$$ A^T = \begin{bmatrix} 1 & 5 & 0\\2 & -1 &-3 \\ 5 & 0 & 3\end{bmatrix}$$

This can now be achieved programmatically by using `np.transpose()` or using the `T` method.

In [ ]:
##sample from prof
A = np.array([
    [1 ,2, 5],
    [5, -1, 0],
    [0, -3, 3]
])
A

array([[ 1,  2,  5],
       [ 5, -1,  0],
       [ 0, -3,  3]])

In [ ]:
AT1 = np.transpose(A)
AT1

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [ ]:
#own sample
O = np.array([
    [5 ,9, 6],
    [2, -2, 12],
    [10, -4, 7]
])
A

array([[ 1,  2,  5],
       [ 5, -1,  0],
       [ 0, -3,  3]])

In [ ]:
OT1 = np.transpose(O)
OT1

array([[ 5,  2, 10],
       [ 9, -2, -4],
       [ 6, 12,  7]])

In [ ]:
AT2 = A.T
AT2

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [ ]:
OT2= O.T
OT2


array([[ 5,  2, 10],
       [ 9, -2, -4],
       [ 6, 12,  7]])

In [ ]:
np.array_equiv(AT1, AT2)

True

In [ ]:
np.array_equiv(OT1, OT2)

True

In [ ]:
B = np.array([
    [1,5,3],
    [1,8,2],
])
B.shape

(2, 3)

In [ ]:
np.transpose(B).shape

(3, 2)

In [ ]:
B.T.shape

(3, 2)

#### Try to create your own matrix (you can try non-squares) to test transposition.

In [ ]:
N = np.array([
    [1,2,4,6],
    [4,9,2,1],
    [4,5,6,8]
])
N.shape

(3, 4)

In [ ]:
np.transpose(N).shape

(4, 3)

In [ ]:
N.T.shape

(4, 3)

## Dot Product / Inner Product

If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In [ ]:
X = np.array([
    [1,2],
    [0,1]
])
Y = np.array([
    [-1,0],
    [2,2]
])

In [ ]:
np.dot(X,Y)

array([[3, 4],
       [2, 2]])

In [ ]:
X.dot(Y)

array([[3, 4],
       [2, 2]])

In [ ]:
X @ Y

array([[3, 4],
       [2, 2]])

In [ ]:
np.matmul(X,Y)

array([[3, 4],
       [2, 2]])

In [ ]:
ritrit = np.array([
    [1,2],
    [3,4]
])
jgiordy = np.array([
    [-5,6],
    [7,8]
])

In [ ]:
np.dot(ritrit,jgiordy)

array([[ 9, 22],
       [13, 50]])

In [ ]:
np.matmul(ritrit,jgiordy)

array([[ 9, 22],
       [13, 50]])

In [ ]:
ritrit @ jgiordy

array([[ 9, 22],
       [13, 50]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$R = \begin{bmatrix}2&5\\4&-3\\0&8\end{bmatrix}, H = \begin{bmatrix}6&5\\2&3\\-3&8\end{bmatrix}, Y = \begin{bmatrix}9&1&5\\2&1&5\end{bmatrix}$$

So in this case $R$ has a shape of $(3,2)$, $H$ has a shape of $(3,2)$ and $Y$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $R \cdot Y$, or $H \cdot Y$.  

In [ ]:
R = np.array([
    [2, 5],
    [4, -3],
    [0, 8]
])
H = np.array([
    [6,5],
    [2,3],
    [-3,8]
])
Y = np.array([
    [9,1,5],
    [2,1,5]
])
print(R.shape)
print(H.shape)
print(Y.shape)

(3, 2)
(3, 2)
(2, 3)


In [ ]:
R @ Y

array([[28,  7, 35],
       [30,  1,  5],
       [16,  8, 40]])

In [ ]:
H @ Y

array([[ 64,  11,  55],
       [ 24,   5,  25],
       [-11,   5,  25]])

If you would notice the shape of the dot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shapes of the matrices used. So recall matrix $A$ with a shape of $(a,b)$ and matrix $B$ with a shape of $(b,c)$, $A \cdot B$ should have a shape $(a,c)$.

In [ ]:
R @ H.T

array([[ 37,  19,  34],
       [  9,  -1, -36],
       [ 40,  24,  64]])

In [ ]:
J = np.array([
    [5,2,3,4]
])
G = np.array([
    [5,0,4,-1]
])
print(J.shape)
print(G.shape)

(1, 4)
(1, 4)


In [ ]:
G.T @ J

array([[25, 10, 15, 20],
       [ 0,  0,  0,  0],
       [20,  8, 12, 16],
       [-5, -2, -3, -4]])

And youcan see that when you try to multiply A and B, it returns `ValueError` pertaining to matrix shape mismatch.

### Rule 2: Dot Product has special properties
Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
1. $A \cdot B \neq B \cdot A$
2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
3. $A\cdot(B+C) = A\cdot B + A\cdot C$
4. $(B+C)\cdot A = B\cdot A + C\cdot A$
5. $A\cdot I = A$
6. $A\cdot \emptyset = \emptyset$


In [21]:
A = np.array([
    [9,2,1],
    [4,8,1],
    [1,1,0]
])
B = np.array([
    [9,1,6],
    [8,1,9],
    [9,0,8]
])
C = np.array([
    [1,1,0],
    [0,1,9],
    [8,0,1]
])

In [22]:
##Example
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.array_equal(a_dot_z,z_mat)

True

In [25]:
A@B 

array([[106,  11,  80],
       [109,  12, 104],
       [ 17,   2,  15]])

In [26]:
B@A

array([[91, 32, 10],
       [85, 33,  9],
       [89, 26,  9]])

In [29]:
A@(B@C)

array([[746, 117, 179],
       [941, 121, 212],
       [137,  19,  33]])

In [30]:
(A@B)@C

array([[746, 117, 179],
       [941, 121, 212],
       [137,  19,  33]])

In [32]:
np.array_equal((A@(B@C)),((A@B)@C))

True

In [33]:
A@(B+C)

array([[123,  22,  99],
       [121,  24, 177],
       [ 18,   4,  24]])

In [34]:
(A@B)+(A@C)

array([[123,  22,  99],
       [121,  24, 177],
       [ 18,   4,  24]])

In [35]:
np.array_equal((A@(B+C)),((A@B)+(A@C)))

True

In [36]:
(B+C)@A

array([[104,  42,  12],
       [ 98,  50,  10],
       [162,  43,  17]])

In [37]:
(B@A)+(C@A)

array([[104,  42,  12],
       [ 98,  50,  10],
       [162,  43,  17]])

In [38]:
np.array_equal(((B+C)@A),((B@A)+(C@A)))

True

In [39]:
A @ np.identity(A.shape[0])

array([[9., 2., 1.],
       [4., 8., 1.],
       [1., 1., 0.]])

In [40]:
np.array_equal((A @ np.identity(A.shape[0])),A)

True

In [41]:
A @ np.zeros(A.shape)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [42]:
np.array_equal((A @ np.zeros(A.shape)),(np.zeros(A.shape)))

True

# Determinants

In [19]:
# 2x2 determinant
C = np.array([
    [5,7],
    [2,3]
    
])
np.linalg.det(C)

0.9999999999999987

In [17]:
# 3x3 determinant
D = np.array([
    [1,4,3],
    [0,3,2],
    [4,5,6]
])
np.linalg.det(D)

3.9999999999999964

In [ ]:
## Now other mathematics classes would require you to solve this by hand, 
## and that is great for practicing your memorization and coordination skills 
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
B = np.array([
    [8,9,5,6],
    [0,3,1,3],
    [3,12,8,5],
    [5,2,3,8]
])
np.linalg.det(B)

766.9999999999992

# Inverse

The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [ ]:
O = np.array([
    [2,7],
    [-3, 8]
])

np.array(O @ np.linalg.inv(O), dtype=int)

array([[1, 0],
       [0, 1]])

In [14]:
N= np.array([
    [2,7, 15, 4, 6],
    [-3, 8, 6, 8,9],
    [5, 4, 7, 1, 2],
    [4, 3, 2, 1, 5],
    [4, 8, 9, 2, 6]

])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0]])

To validate the wether if the matric that you have solved is really the inverse, we follow this dot product property for a matrix $N$:
$$N\cdot N^{-1} = I$$

In [ ]:
M = np.array([
    [1,7],
    [-3, 5]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
P= np.array([
    [6 ,9, 0],
    [4, 2,-1],
    [3,4,7]
])
Q = np.linalg.inv(P)
Q

array([[-0.10526316,  0.36842105,  0.05263158],
       [ 0.18128655, -0.24561404, -0.03508772],
       [-0.05847953, -0.01754386,  0.14035088]])

In [ ]:
P @ Q

array([[ 1.00000000e+00, -1.11022302e-16,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -5.55111512e-17,  1.00000000e+00]])

In [43]:
squad = np.array([
    [1.0, 1.0, 0.5],
    [0.8, 0.9, 0.9],
    [0.2, 0.2, 0.6]
])
weights = np.array([
    [0.2, 0.3, 0.6]
])
p_grade = squad @ weights.T
p_grade


array([[0.8 ],
       [0.97],
       [0.46]])