<a href="https://colab.research.google.com/github/nyxx08/LinearAlgebra_2ndSem/blob/main/Assignment_3_sabioipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra For ChE
## Laboratory 2 Matrices


Now that you have a fundamental knowledge about Python, we'll try to look into greater dimensions.

##Objectives
At the end of this activity you will be able to:

Be familiar with matrices and their relation to linear equations.
Perform basic matrix operations.
Program and translate matrix equations and operations using Python.

# Discussion

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

## Matrices


The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also handy representations of complex equations or multiple inter-related equations from 2-dimensional equations to even hundreds and thousands of them.

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. \\
C = \left\{
    \begin{array}\
        w-2x+3y-4z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right.$$



We could see that A is a system of 2 equations with 2 parameters. While B  is a system of 3 equations with 3 parameters. We can represent them as matrices as:

:$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}\\
C=\begin{bmatrix} 1 & -2 & 3 & -4 \\ 3 & -1 & -2 & 1 \\ 2 & -1 & 3 & -2\end{bmatrix}
$$


$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


### Declaring Matrices

These elements are arranged and ordered in rows and columns which form the list/array-like structure of matrices. And just like arrays, these elements are indexed according to their position with respect to their rows and columns. This can be represented just like the equation below. Whereas  A  is a matrix consisting of elements denoted by  ai,j . Denoted by  i  is the number of rows in the matrix while  j  stands for the number of columns.
Do note that the  size  of a matrix is  i×j .

In [4]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
## Declaring a 2 x 2 matrix
A = np.array ([
    [1,2],
    [3,1]
])
describe_mat(A)


Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



In [ ]:
#Declaring a 2 x 3 matrix
G= np.array([
    [1,1,3],
    [3,1,4]
])
describe_mat(A)
A.shape

Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



(2, 2)

In [ ]:
H = np.array([1,2,3,4,5])
describe_mat(A)
A.shape

Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



(2, 2)

## Categorizing Matrices

There are several ways of classifying matrices. Once could be according to their shape and another is according to their element values. We'll try to go through them.

## According to Shape

### Row and Column Matrices

**Row** and **column** matrices are common in vector and matrix computations. They can also represent row and column spaces of a bigger vector space. Row and column matrices are represented by a single column or single row. So with that being, the shape of row matrices would be $1 \times j$ and column matrices would be $i \times 1$.

In [ ]:
rowmatrix1D = np.array ([1,2,3-4
])
rowmatrix2D = np.array ([1,2,3,-4
                        
])
describe_mat(rowmatrix1D)
describe_mat(rowmatrix2D)

Matrix:
[ 1  2 -1]

Shape:	(3,)
Rank:	1
Matrix:
[ 1  2  3 -4]

Shape:	(4,)
Rank:	1


In [6]:
#Declaring a column matrix
colmat = np. array ([
                    [1],
                    [2],
                    [56]
                  ])
describe_mat(colmat)

Matrix:
[[ 1]
 [ 2]
 [56]]

Shape:	(3, 1)
Rank:	2



###Square Matrices

Square matrices are that have the same row and column sizes. We could say a matrix is square if i = j. We can tweak our matrix descriptor function to determine square matrices

In [ ]:
def describe_mat (matrix): 
  is_square =True if matrix.shape[0]==matrix.shape[1] else False 
  print (f'Matrix:\n{matrix}\n\nshape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square:{is_square}\n')


In [8]:
sq_mat = np.array([
                        [1,3,8],
                        [5,4,7],
                        [5,4,5]
])
nonsq_mat = np.array ([
                        [4,5,6],
                        [2,3,5]
])
describe_mat(sq_mat)
describe_mat(nonsq_mat)

Matrix:
[[1 3 8]
 [5 4 7]
 [5 4 5]]

Shape:	(3, 3)
Rank:	2

Matrix:
[[4 5 6]
 [2 3 5]]

Shape:	(2, 3)
Rank:	2



In [10]:
T= np.array([
             [3,3,3],
             [2,2,2],
             [1,1,1]
])
T
describe_mat(T)

Matrix:
[[3 3 3]
 [2 2 2]
 [1 1 1]]

Shape:	(3, 3)
Rank:	2



In [12]:
F= np.array([
             [3,3,3],
             [2,2,2]
])
F
describe_mat(F)   

Matrix:
[[3 3 3]
 [2 2 2]]

Shape:	(2, 3)
Rank:	2



### According to element values

#### Null Matrix

A Null Matrix is a matrix that has no elements. It is always a subspace of any vector or matrix.

In [15]:
def describe_mat (matrix):

  if matrix.size > 0:
    is_square = True if matrix.shape [0] == matrix.shape[1] else False
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n') 
  else:
    print('Null Matrix')

In [16]:
n_mat = np.array ([])
describe_mat(n_mat)

Null Matrix


#### Zero Matrix

A zero matrix can be any rectangular matrix but with all elements having a value of 0.

In [17]:
zmr = np.zeros((1,2))
zms = np.zeros((2,2))
zrm = np.zeros((3,2))

print(f' Zero Row Matix: \n{zmr}')
print(f' Zero Square Matrix: \n{zms}')
print(f' Zero Rectangular Matrix: \n{zrm}')

 Zero Row Matix: 
[[0. 0.]]
 Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
 Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


####  Ones Matrix

A ones matrix, just like the zero matrix, can be any rectangular matrix but all of its elements are 1s instead of 0s.

In [19]:
omr = np.ones((1,2))
oms = np.ones((2,2))
omrc = np.ones((3,2))

print(f' Ones Row Matix: \n{omr}')
print(f' Ones Square Matrix: \n{oms}')
print(f' Ones Rectangular Matrix: \n{omrc}')

 Ones Row Matix: 
[[1. 1.]]
 Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
 Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


#### Diagonal Matrix

A diagonal matrix is a square matrix that has values only at the diagonal of the matrix.

In [ ]:
# Diagonal Matrix
np.array([
  [2,0,0],
  [0,3,0],
  [0,0,5]
])

# a[1,1], a[2,2], a[3,3], ... a[n-1,-1]

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [21]:
d = np.diag([2,9,16,27]) 
#np.diag(d).shape == d.shape [0] I d.shape[1]
d



array([[ 2,  0,  0,  0],
       [ 0,  9,  0,  0],
       [ 0,  0, 16,  0],
       [ 0,  0,  0, 27]])

#### Identity Matrix

An identity matrix is a special diagonal matrix in which the values at the diagonal are ones.

In [ ]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [22]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

###Upper triangular matrix

An upper triangular matrix is a matrix that has no values below the diagonal.

In [ ]:
np.array([

[1,2,3,4],
[0,3,1,-1],
[0,0,5,2],
[0,0,0,2]

])

array([[ 1,  2,  3,  4],
       [ 0,  3,  1, -1],
       [ 0,  0,  5,  2],
       [ 0,  0,  0,  2]])

###Lower triangular matrix

A lower triangular matrix is a matrix that has no values above the diagonal.

In [23]:
np. array([
  [1, 0, 0, 0],
  [7, 8, 0, 0],
  [10, 9, 8, 0],
  [9, 8, 5, 4]
])

array([[ 1,  0,  0,  0],
       [ 7,  8,  0,  0],
       [10,  9,  8,  0],
       [ 9,  8,  5,  4]])

##Practice

1 Given the linear combination below, try to create a corresponding matrix representing it.


:$$\theta = 5x + 3y - z$$

:$$
θ=\begin{bmatrix} 5 & 3 &-1\end{bmatrix} \\
$$

In [ ]:
θ = np.array([
    [5,3,-1]
])
θ

array([[ 5,  3, -1]])

2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.


$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [ ]:
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
A= np.array ([
              [1,2,1],
              [0,4,-3],
              [0,0,10]
])
A
describe_mat(A)

Matrix:
[[ 1  2  1]
 [ 0  4 -3]
 [ 0  0 10]]

Shape:	(3, 3)
Rank:	2



Matrix A is an upper triangular matrix

3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown


In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])


:$$
G=\begin{bmatrix} 1 & 7 & 8 \\ 2 & 2 & 2 \\ 4 & 6 & 7 \end{bmatrix} 
$$

$$
G = \left\{\begin{array}
1x_1 + 7x_2 +8x_3\\
2x_1+2x_2 - 2x_3\\
4x_1 + 6x_2 + 7x_3
\end{array}\right.
$$

4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.


In [ ]:
H = np.tril(G)
H

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

:$$
H=\begin{bmatrix} 1 & 0 & 0 \\ 2 & 2 & 0 \\ 4 & 6 & 7 \end{bmatrix} 
$$

$$
H = \left\{\begin{array}
1x_1  \\
2x_1+2x_2 \\
4x_1 + 6x_2 + 7x_3
\end{array}\right.
$$

## Matrix Algebra

### Addition

In [28]:
Jgio = np.array([
    [0, 9],
    [0, 8],
    [0, 1]
])
RO = np.array([
    [1, 0],
    [0, 8],
    [0, 2]
])
Jgio+RO

array([[ 1,  9],
       [ 0, 16],
       [ 0,  3]])

In [29]:
3+Jgio 

array([[ 3, 12],
       [ 3, 11],
       [ 3,  4]])

###Subtraction

In [30]:
RO - Jgio

array([[ 1, -9],
       [ 0,  0],
       [ 0,  1]])

In [31]:
5-RO

array([[ 4,  5],
       [ 5, -3],
       [ 5,  3]])

### Element-Wise Multiplication

In [32]:
Jgio*RO
np.multiply(Jgio,RO)

array([[ 0,  0],
       [ 0, 64],
       [ 0,  2]])

In [33]:
45*RO

array([[ 45,   0],
       [  0, 360],
       [  0,  90]])

In [34]:
alpha=10**-10
Jgio/(alpha+RO)

array([[0.e+00, 9.e+10],
       [0.e+00, 1.e+00],
       [0.e+00, 5.e-01]])

In [35]:
np.add(RO,Jgio)

array([[ 1,  9],
       [ 0, 16],
       [ 0,  3]])

### Activity

####Task 1

Create a function named `mat_desc()` that througouhly describes a matrix, it should: <br>
1. Displays the shape, size, and rank of the matrix. <br>
2. Displays whether the matrix is square or non-square. <br>
3. Displays whether the matrix is an empty matrix. <br>
4. Displays if the matrix is an identity, ones, or zeros matrix <br>
   
Use 3 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [37]:
## Function area
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline
def mat_desc (matrix):
  if matrix.size > 0:
    if matrix.shape [0] == matrix.shape[1]:
      s = "Square."
    else:
      s = "Non-square."
    if np.all(matrix == np.identity(matrix.shape[0])):
      sp = "Identity Matrix."
    elif np.all(matrix == np.zeros(matrix.shape)):
      sp = "Zero Matrix."
    elif np.all(matrix == np.ones(matrix.shape)):
      sp = "Ones Matrix."
    else:
      sp = "None."
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nSquare?: {s}\nSpecial Characteristics: {sp}') 
  else:
    print('Matrix is Empty')
      

In [38]:
## Matrix declarations
hi = np.array([
    [3,1,2,4],
    [4,7,9,6],
    [9,1,6,7]
])
one = np.array([
    [1,1,1,1,1],
    [1,1,1,1,1],
    [1,1,1,1,1],
    [1,1,1,1,1],
])
id = np.array([
    [1,0,0,0],
    [0,1,0,0],
    [0,0,1,0],
    [0,0,0,1]
])

In [ ]:
## Test Areas

In [39]:
mat_desc(hi)

Matrix:
[[3 1 2 4]
 [4 7 9 6]
 [9 1 6 7]]

Shape:	(3, 4)
Rank:	2
Square?: Non-square.
Special Characteristics: None.


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if sys.path[0] == '':


In [40]:
mat_desc(one)

Matrix:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

Shape:	(4, 5)
Rank:	2
Square?: Non-square.
Special Characteristics: Ones Matrix.


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if sys.path[0] == '':


In [41]:
mat_desc(id)

Matrix:
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

Shape:	(4, 4)
Rank:	2
Square?: Square.
Special Characteristics: Identity Matrix.


#### Task 2

Create a function named `mat_operations()` that takes in two matrices and input parameters it should:<br>
 1. Determine if the matrices are viable for operation and returns your own error message if they are not viable.
 2. Returns the sum of the matrices.
 3. Returns the difference of the matrices.
 4. Returns the element-wise multiplication of the matrices.
 5. Returns the element-wise division of the matrices.

Use 3 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [42]:
# Function Area
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline
def mat_operations(matA, matB):
  op = input("Enter operation(+,-,*,/): ")
  if matA.shape == matB.shape:
    # proceed to operations
    if op == '+':
      return matA + matB
    elif op == '-':
      return matA - matB
    elif op == '*':
      return matA * matB
    elif op == '/':
      return matA / matB
    else:
      print("The matrices are viable but you have not inputted a correct operation.")
  else:
    print("Huhuhu.The matrices are not viable.")

In [43]:
#matrix declarations
A = np.array([
    [1,1,1,1],
    [1,1,1,1],  
    [1,1,1,1],
    [1,1,1,1]
])
B = np.array([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
])
C = np.array([
    [3,3,3,3,3],
    [3,3,3,3,3],
    [3,3,3,3,3]
])
D = np.array([
    [4,4,4,4,4],
    [4,4,4,4,4],
    [4,4,4,4,4]
])

In [44]:
mat_operations(A,C)

Enter operation(+,-,*,/): /
Huhuhu.The matrices are not viable.


In [45]:
mat_operations(D, C)

Enter operation(+,-,*,/): /


array([[1.33333333, 1.33333333, 1.33333333, 1.33333333, 1.33333333],
       [1.33333333, 1.33333333, 1.33333333, 1.33333333, 1.33333333],
       [1.33333333, 1.33333333, 1.33333333, 1.33333333, 1.33333333]])

In [46]:
mat_operations(A,B)

Enter operation(+,-,*,/): -


array([[-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1]])

### Conclusion

For your conclusion synthesize the concept and application of the laboratory. Briefly discuss what you have learned and achieved in this activity. Also answer the question: "How can matrix operations solve problems in technology?".